# Generated by Django 5.1.2 on 2024-10-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
